InsureApp/Controllers/OdemelerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using InsureApp.Business.Abstract;
using InsureApp.Entities.Concrete;
using InsureApp.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Syncfusion.HtmlConverter;
using Syncfusion.Pdf;

namespace InsureApp.Controllers
{
    public class OdemelerController : Controller
    {

        private IOdemelerService _odemelerService;
        private IMusteriService _musteriservice;
        private IPoliceService _policeService;

        public OdemelerController(IOdemelerService odemelerService,
                                  IPoliceService policeService,
                                  IMusteriService musteriService)
        {
            _odemelerService = odemelerService;
            _policeService = policeService;
            _musteriservice = musteriService;
        }

        public ActionResult Index(int page = 1, int musteri = 0)
        {
            int pageSize = 10;
            var odeme = _odemelerService.GetByMusteriId(musteri);
            OdemelerListViewModel model = new OdemelerListViewModel()
            {
                Odemeler = FixModel(odeme.Skip((page - 1) * pageSize).Take(pageSize).ToList()),
                PageCount = (int)Math.Ceiling(odeme.Count / (double)pageSize),
                PageSize = pageSize,
                CurrentCategory = musteri,
                CurrentPage = page
            };
            return View(model);
        }

        private List<OdemelerModel> FixModel(List<Odemeler> toList)
        {
            var result = new List<OdemelerModel>();
            foreach (var item in toList)
            {
                var row = new OdemelerModel();
                var musteri = _musteriservice.GetById(item.Musteri_id);
                var police = _policeService.GetById(item.Police_no);

                row.SigortaBedeli = police.Sigorta_bedeli;
                row.Ad = musteri.Isim;
                row.Soyad = musteri.Soyisim;
                row.FullName = string.Format("{0} {1}", row.Ad, row.Soyad);
                //row.Musteri_id = item.Musteri_id;
                row.Odeme_id = item.Odeme_id;
                row.Odeme_tarihi = item.Odeme_tarihi;
                row.Odenen_tutar = item.Odenen_tutar;
                row.Police_no = police.Police_no;

                result.Add(row);
            }

            return result;
        }

        public ActionResult Add()
        {
            var model = new OdemelerAddViewModel()
            {
                Odemeler = new Odemeler(),
                MusterilerList = FixMusterModel(_musteriservice.GetAll()),
                Police = _policeService.GetAll()
            };
            return View(model);
        }

        private List<MusteriModel> FixMusterModel(List<Musteri> list)
        {
            var result = new List<MusteriModel>();
            foreach (var item in list)
            {
                var row = new MusteriModel();
                //row.FullName = item.Isim + item.Soyisim;
                row.FullName = string.Format("{0}  {1}", item.Isim, item.Soyisim);
                row.Musteri_id = item.Musteri_id;

                result.Add(row);
            }

            return result;
        }

        [HttpPost]
        public ActionResult Add(Odemeler odemeler)
        {
            if (ModelState.IsValid)
            {
                _odemelerService.Add(odemeler);

                // TempData.Add("message","Poliçe başarıyla eklendi");

            }

            return RedirectToAction("Add");

        }

        public ActionResult Update(int odeme_id)

        {
            var model = new OdemelerUpdateViewModel()
            {
                Odemeler = _odemelerService.GetById(odeme_id),
                Musteri = _musteriservice.GetAll(),
                Police =  _policeService.GetAll(),

            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Update(Odemeler odemeler)
        {
            if (ModelState.IsValid)
            {
                _odemelerService.Update(odemeler);
                //TempData.Add("Mesaj", "Müşteri güncelleme işlemi gerçekleşti.");
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int odeme_id)
        {
            _odemelerService.Delete(odeme_id);
            //TempData.Add("Mesaj", "Müşteri silme işlemi gerçekleşti.");
            return RedirectToAction("Index");
        }
    }
}

InsureApp/Views/Odemeler/Add.cshtml
@using System.Threading.Tasks
@using InsureApp.Models
@model InsureApp.Models.OdemelerAddViewModel

@{
    ViewBag.Title = "Ödeme Tanımlama";
    Layout = "~/Views/_AdminLayout.cshtml";
}

<h2>Yeni bir ödeme tanımla</h2>

<form asp-controller="Odemeler" asp-action="Add" method="post">

    <div class="form-group">
        <label asp-for="Odemeler.Police_no">Poliçe No :</label>
        <input asp-for="Odemeler.Police_no" class="form-control" placeholder="Poliçe No"/>
        <span asp-validation-for="Odemeler.Police_no"></span>
    </div>

    <div class="form-group">
        <label asp-for="Odemeler.Musteri_id">Müşteri Ad Soyad :</label>
        <select asp-for="Odemeler.Musteri_id" class="form-control h-100 font-weight-bold"
                asp-items="@(new SelectList(Model.MusterilerList, "Musteri_id", "FullName"))"></select>
        <span asp-validation-for="Odemeler.Musteri_id"></span>
    </div>
    <div class="form-group">
        <label asp-for="Odemeler.Odenen_tutar">Ödenen Tutar :</label>
        <input asp-for="Odemeler.Odenen_tutar" class="form-control" placeholder="Ödenen Tutar" />
        <span asp-validation-for="Odemeler.Odenen_tutar"></span>
    </div>
    <div class="form-group">
        <label asp-for="Odemeler.Odeme_tarihi">Ödeme Tarihi :</label>
        <input asp-for="Odemeler.Odeme_tarihi" class="form-control" placeholder="Ödeme Tarihi" />
        <span asp-validation-for="Odemeler.Odeme_tarihi"></span>
    </div>

    <input type="submit" value="EKLE" class="btn btn-xs btn-success" />

</form>

InsureApp/Views/Odemeler/Index.cshtml
@using InsureApp.Business.Concrate
@using InsureApp.DataAccess.Concrate.EntityFramework
@using InsureApp.Entities.Concrete
@using Microsoft.Ajax.Utilities
@model InsureApp.Models.OdemelerListViewModel

@{
    ViewBag.Title = "Ödeme İşlemleri";
    Layout = "~/Views/_AdminLayout.cshtml";
}
<a class="btn btn-xs btn-success" asp-controller="Odemeler" asp-action="Add">Yeni Ödeme Tanımla</a>
<div>
    <table class="table table-hover table-striped" style="font-size:small">
        <tr>
            <td>Poliçe No</td>
            <td>Musteri Adı</td>
            <td>Ödenen Tutar</td>
            <td>Ödeme Tarihi</td>
            <td></td>
            <td></td>
        </tr>
        @foreach (var odemeler in Model.Odemeler)
        {
            <tr>
                <td>@odemeler.Police_no</td>
                <td>@odemeler.FullName</td>
                <td>@odemeler.Odenen_tutar</td>
                <td>@odemeler.Odeme_tarihi</td>

                <td><a class="btn btn-xs btn-info" asp-controller="Odemeler" asp-action="Update" asp-route-odeme_id="@odemeler.Odeme_id">GÜNCELLE</a></td>
                <td><a class="btn btn-xs btn-danger" asp-controller="Odemeler" asp-action="Delete" asp-route-odeme_id="@odemeler.Odeme_id">SİL</a></td>
            </tr>
        }
    </table>
</div>

InsureApp/Views/Odemeler/Update.cshtml
@using System.Threading.Tasks
@using InsureApp.Models
@model InsureApp.Models.OdemelerUpdateViewModel

@{
    ViewBag.Title = "Müşteri Güncelleme";
    Layout = "~/Views/_AdminLayout.cshtml";
}

<h2>Ödeme Güncelle</h2>

<form asp-controller="Odemeler" asp-action="Update" method="post">

    <div class="form-group">
        <label asp-for="Odemeler.Odenen_tutar">Ödenen Tutar :</label>
        <input asp-for="Odemeler.Odenen_tutar" class="form-control" placeholder="Ödenen Tutar"/>
        <span asp-validation-for="Odemeler.Odenen_tutar"></span>
    </div>
    <div class="form-group">
        <label asp-for="Odemeler.Odeme_tarihi">Ödeme Tarihi :</label>
        <input asp-for="Odemeler.Odeme_tarihi" class="form-control" placeholder="Ödeme Tarihi"/>
        <span asp-validation-for="Odemeler.Odeme_tarihi"></span>
    </div>

    <input type="submit" value="GÜNCELLE" class="btn btn-xs btn-success"/>

</form>