InsureApp/Controllers/AracController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InsureApp.Business.Abstract;
using InsureApp.Entities.Concrete;
using InsureApp.Models;

namespace InsureApp.Controllers
{
    public class AracController:Controller
    {
        private IAracService _aracService;
        private IPoliceService _policeService;

        public AracController(IPoliceService policeService, IAracService aracService)
        {
            _policeService = policeService;
            _aracService = aracService;
        }

        public ActionResult Index(int page = 1, int policeno = 0)
        {
            //int pageSize = 10;
            var araclar = _aracService.GetAll();
            AracListViewModel model = new AracListViewModel()
            {
                Arac = araclar
              
            };
            return View(model);
            //int pageSize = 10;
            //var arac = _aracService.GetByPoliceNo(policeno);
            //AracListViewModel model = new AracListViewModel()
            //{
            //    Arac = arac.Skip((page - 1) * pageSize).Take(pageSize).ToList(),
            //    PageCount = (int)Math.Ceiling(arac.Count / (double)pageSize),
            //    PageSize = pageSize,
            //    CurrentCategory = policeno,
            //    CurrentPage = page
            //};
            //return View(model);
        }
        public ActionResult Add()
        {
            var model = new AracAddListViewModel()
            {
                Arac = new Arac(),
                Police = _policeService.GetAll()
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Add(Arac arac)
        {
            if (ModelState.IsValid)
            {
                _aracService.Add(arac);
                // TempData.Add("message","Poliçe başarıyla eklendi");

            }
            return RedirectToAction("Add");

        }
        public ActionResult Update()
        {
            return View();
        }
    }
}

InsureApp/Controllers/PoliceController.cs
using InsureApp.Business.Abstract;
using InsureApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InsureApp.Entities.Concrete;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace InsureApp.Controllers
{
    public class PoliceController:Controller
    {
        private IPoliceService _policeService;
        private IPoliceTuruService _policeturuservice;
        private IMusteriService _musteriservice;
        private IAracService _aracService;
        private IKonut_DigerService _konutDigerService;
        private IOdemelerService _odemelerService;

        public PoliceController(IPoliceService policeService, 
                                IPoliceTuruService policeturuService, 
                                IMusteriService musteriService,
                                IAracService aracService,
                                IKonut_DigerService konutDigerService,
                                IOdemelerService odemelerService)
        {
            _policeService = policeService;
            _policeturuservice = policeturuService;
            _musteriservice = musteriService;
            _aracService = aracService;
            _konutDigerService = konutDigerService;
            _odemelerService = odemelerService;
        }

        public ActionResult Index(int page = 1, int policeturu = 0)
        {
            int pageSize = 10;
            var police = _policeService.GetByPolice_Turu(policeturu);
            var policTuru = _policeturuservice.GetByPolice_Turu(policeturu).FirstOrDefault();
            PoliceListViewModel model = new PoliceListViewModel
            {
                Police = FixModel(police.Skip((page -1) * pageSize).Take(pageSize).ToList()),
                PageCount = (int)Math.Ceiling(police.Count / (double)pageSize),
                PageSize = pageSize,
                CurrentCategory = policTuru != null ? policTuru.Policetur_id : 0,
                CurrentCategoryText = policTuru != null ? policTuru.Police_turu : string.Empty,
                CurrentPage = page
            };
            return View(model);
        }

        private List<PoliceModel> FixModel(List<Police> toList)
        {
            var result = new List<PoliceModel>();
            foreach (var item in toList)
            {
                var row = new PoliceModel();
                var musteri = _musteriservice.GetById(item.Musteri_id);
                var policeturu = _policeturuservice.GetById(item.Policetur_id);

                row.PoliceTuru = policeturu.Police_turu;
                row.Ad = musteri.Isim;
                row.Soyad = musteri.Soyisim;
                row.Policetur_id = policeturu.Policetur_id;
                row.Baslangic_tarihi = item.Baslangic_tarihi;
                row.Bitis_tarihi = item.Bitis_tarihi;
                row.Vize_tarihi = item.Vize_tarihi;
                row.Sigorta_bedeli = item.Sigorta_bedeli;
                row.Police_no = item.Police_no;
                row.FullName = string.Format("{0} {1}",row.Ad,row.Soyad);
                result.Add(row);
            }

            return result;
        }


        public ActionResult Add()
        {
            var model = new PoliceAddViewListModel
            {
                Police = new Police(),
                PoliceTuru = _policeturuservice.GetAll(),
                MusterilerList = FixMusterModel( _musteriservice.GetAll())
            };
            return View(model);
        }

        private List<MusteriModel> FixMusterModel(List<Musteri> list)
        {
            var result = new List<MusteriModel>();
            foreach (var item in list)
            {
               var row = new MusteriModel();
               //row.FullName = item.Isim + item.Soyisim;
               row.FullName = string.Format("{0}  {1}", item.Isim, item.Soyisim);
               row.Musteri_id = item.Musteri_id;
               result.Add(row);
            }

            return result;
        }

        [HttpPost]
        public ActionResult Add(Police police)
        {
            if (ModelState.IsValid)
            {

                
                _policeService.Add(police);
                // TempData.Add("message","Poliçe başarıyla eklendi");
                
            }
            return RedirectToAction("Add");

        }

        public ActionResult Update(int police_No)
             
        {
            var model = new PoliceUpdateViewModel()
            {
                Police = _policeService.GetById(police_No),
                Musteri = _musteriservice.GetAll(),
                PoliceTuru = _policeturuservice.GetAll()
               
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Update(Police police)
        {
            if (ModelState.IsValid)
            {
                _policeService.Update(police);
                //TempData.Add("Mesaj", "Müşteri güncelleme işlemi gerçekleşti.");
            }
            return RedirectToAction("Update");
        }

        public ActionResult Delete(int Police_no)
        {
            _aracService.DeleteByPoliceId(Police_no);
            _konutDigerService.DeleteByPoliceId(Police_no);
            _odemelerService.DeleteByPoliceId(Police_no);
            _policeService.Delete(Police_no);
            //TempData.Add("Mesaj", "Müşteri silme işlemi gerçekleşti.");
            return RedirectToAction("Index");
        }
    }
}

InsureApp/Views/Police/Add.cshtml
@using System.Threading.Tasks
@using InsureApp.Models
@model InsureApp.Models.PoliceAddViewListModel

@{
    ViewBag.Title = "Poliçe Ekleme";
    Layout = "~/Views/_AdminLayout.cshtml";
}

<h2>Yeni bir poliçe ekle</h2>

<form asp-controller="Police" asp-action="Add" method="post">
    <div class="form-group" >
        <label asp-for="Police.Musteri_id">Müşteri Ad Soyad :</label>
        <select asp-for="Police.Musteri_id" class="form-control h-100 font-weight-bold"
                asp-items="@(new SelectList(Model.MusterilerList,"Musteri_id","FullName"))"></select>
        <span asp-validation-for="Police.Musteri_id"></span>
    </div>

    <div class="form-group">
        <label asp-for="Police.Policetur_id">Poliçe Türü :</label>
        <select asp-for="Police.Policetur_id" class="form-control h-100 font-weight-bold"
                asp-items="@(new SelectList(Model.PoliceTuru,"Policetur_id","Police_turu"))"></select>
        <span asp-validation-for="Police.Policetur_id"></span>
    </div>

    <div class="form-group">
        <label asp-for="Police.Baslangic_tarihi">Başlangıç Tarihi :</label>
        <input asp-for="Police.Baslangic_tarihi" class="form-control" placeholder="Başlangıç Tarihi" />
        <span asp-validation-for="Police.Baslangic_tarihi"></span>
    </div>
    <div class="form-group">
        <label asp-for="Police.Bitis_tarihi">Bitiş Tarihi :</label>
        <input asp-for="Police.Bitis_tarihi" class="form-control" placeholder="(---)--- -- --)" />
        <span asp-validation-for="Police.Bitis_tarihi"></span>
    </div>
    <div class="form-group">
        <label asp-for="Police.Vize_tarihi">Vize Tarihi :</label>
        <input asp-for="Police.Vize_tarihi" class="form-control" placeholder="Vize Tarihi" />
        <span asp-validation-for="Police.Vize_tarihi"></span>
    </div>
    <div class="form-group">
        <label asp-for="Police.Sigorta_bedeli">Sigorta Bedeli :</label>
        <input asp-for="Police.Sigorta_bedeli" class="form-control" placeholder="Açıklama" />
        <span asp-validation-for="Police.Sigorta_bedeli"></span>
    </div>

    <input type="submit" value="EKLE" class="btn btn-xs btn-success" />

</form>

InsureApp/Views/Police/Index.cshtml
@using InsureApp.Business.Concrate
@using InsureApp.DataAccess.Concrate.EntityFramework
@using InsureApp.Entities.Concrete
@using Microsoft.Ajax.Utilities
@model InsureApp.Models.PoliceListViewModel

@functions {
public int Toplam { get; set; }
}

@{
    ViewBag.Title = "Police İşlemleri";
    Layout = "~/Views/_LayoutPage.cshtml";
}

<a class="btn btn-xs btn-success" asp-controller="Police" asp-action="Add">Yeni Poliçe Ekle</a>
<a class="btn btn-xs btn-success" asp-controller="Konut_Diger" asp-action="Add">Konut Bilgileri Ekle</a>
<a class="btn btn-xs btn-success" asp-controller="Konut_Diger" asp-action="Index">Konut Bilgilerini Listele</a>
<a class="btn btn-xs btn-success" asp-controller="Arac" asp-action="Add">Araç Bilgileri Ekle</a>
<a class="btn btn-xs btn-success" asp-controller="Arac" asp-action="Index">Araç Bilgilerini Listele</a>

<div>
    <table class="table table-hover table-striped" style="font-size:small">
        <tr>
            <td>Adı Soyadı</td>
            <td>Poliçe No</td>
            <td>Poliçe Türü</td>
            <td>Başlangıç Tarihi</td>
            <td>Bitiş Tarihi</td>
            <td>Vize Tarihi</td>
            <td>Sigorta Bedeli</td>
            <td></td>
            <td></td>
        </tr>
        
        @foreach (var police in Model.Police)
        {
            Toplam += police.Sigorta_bedeli;
            
            <tr>
                <td>@police.FullName</td>
                <td>@police.Police_no</td>
                <td>@police.PoliceTuru</td>
                <td>@police.Baslangic_tarihi.ToShortDateString()</td>
                <td>@police.Bitis_tarihi.ToShortDateString()</td>
                <td>@police.Vize_tarihi.ToShortDateString()</td>
                <td>@police.Sigorta_bedeli</td>
                <td><a class="btn btn-xs btn-info" asp-controller="Police" asp-action="Update" asp-route-Police_no="@police.Police_no">GÜNCELLE</a></td>
                <td><a class="btn btn-xs btn-danger" asp-controller="Police" asp-action="Delete" asp-route-Police_no="@police.Police_no">SİL</a></td>
            </tr>
        }

    </table>
    <div style="font-size: large" align="center">
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        Toplam Sigorta Bedeli :&nbsp @Toplam.ToString()
    </div>
</div>
<police-list-pager current-police="@Model.CurrentCategory"
                   current-page="@Model.CurrentPage"
                   page-count="@Model.PageCount"
                   page-size="@Model.PageSize"></police-list-pager>

InsureApp/Views/Police/Update.cshtml
@using System.Threading.Tasks
@using InsureApp.Models
@model InsureApp.Models.PoliceUpdateViewModel

@{
    ViewBag.Title = "Poliçe Güncelleme";
    Layout = "~/Views/_AdminLayout.cshtml";
}

<h2>Poliçe Güncelle</h2>

<form asp-controller="Police" asp-action="Update" method="post">
    <div class="form-group">
        <label asp-for="Police.Baslangic_tarihi"></label>
        <input asp-for="Police.Baslangic_tarihi" class="form-control" placeholder="Başlangıç Tarihi:" />
        <span asp-validation-for="Police.Baslangic_tarihi"></span>
    </div>
    <div class="form-group">
        <label asp-for="Police.Bitis_tarihi"></label>
        <input asp-for="Police.Bitis_tarihi" class="form-control" placeholder="Bitiş Tarihi:" />
        <span asp-validation-for="Police.Bitis_tarihi"></span>
    </div>
    <div class="form-group">
        <label asp-for="Police.Vize_tarihi"></label>
        <input asp-for="Police.Vize_tarihi" class="form-control" placeholder="Vize Tarihi:" />
        <span asp-validation-for="Police.Vize_tarihi"></span>
    </div>
    <div class="form-group">
        <label asp-for="Police.Sigorta_bedeli"></label>
        <input asp-for="Police.Sigorta_bedeli" class="form-control" placeholder="Sigorta Bedeli:" />
        <span asp-validation-for="Police.Sigorta_bedeli"></span>
    </div>
   

    <input type="hidden" asp-for="Police.Police_no" />
    <input type="submit" value="GÜNCELLE" class="btn btn-xs btn-success" />

</form>