InsureApp/Controllers/AdminController.cs
using InsureApp.Business.Abstract;
using InsureApp.Entities.Concrete;
using InsureApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InsureApp.Controllers
{
    public class AdminController:Controller
    {
        private IMusteriService _musteriService;


        public AdminController(IMusteriService musteriService)
        {
            _musteriService = musteriService; 


        }

        public ActionResult Index()
        {
            var musteriListViewModel = new MusteriListViewModel
            {
                Musteri = _musteriService.GetAll()
            };
            return View(musteriListViewModel); 
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(Musteri musteri)
        {
            if (ModelState.IsValid)
            {
                _musteriService.Add(musteri);
                return RedirectToAction("Index");
                //TempData.Add("Mesaj", "Müşteri ekleme işlemi gerçekleşti.");
            }
            return View();
        }


        public ActionResult Update(int musteriId)

        {
            var model = new MusteriUpdateViewModel
            {
                Musteri = _musteriService.GetById(musteriId),
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Update(Musteri musteri)
        {
            if (ModelState.IsValid)
            {
                _musteriService.Update(musteri);
                //TempData.Add("Mesaj", "Müşteri güncelleme işlemi gerçekleşti.");
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int musteriId)
        {
            _musteriService.Delete(musteriId);
            //TempData.Add("Mesaj", "Müşteri silme işlemi gerçekleşti.");
            return RedirectToAction("Index");
        }
    }
}

InsureApp/Controllers/Konut_DigerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InsureApp.Business.Abstract;
using InsureApp.Entities.Concrete;
using InsureApp.Models;

namespace InsureApp.Controllers
{
    public class Konut_DigerController : Controller
    {
        private IKonut_DigerService _konutDigerService;
        private IPoliceService _policeService;

        public Konut_DigerController(IKonut_DigerService konutDigerService, IPoliceService policeService)
        {
            _konutDigerService = konutDigerService;
            _policeService = policeService;
        }
        
        public ActionResult Index(int page = 1, int policeno = 0)
        {
            //int pageSize = 10;
            var konutlar = _konutDigerService.GetAll();
            Konut_DigerListViewModel model = new Konut_DigerListViewModel()
            {
                Konut_Diger = konutlar

            };
            return View(model);
            //int pageSize = 10;
            //var arac = _aracService.GetByPoliceNo(policeno);
            //AracListViewModel model = new AracListViewModel()
            //{
            //    Arac = arac.Skip((page - 1) * pageSize).Take(pageSize).ToList(),
            //    PageCount = (int)Math.Ceiling(arac.Count / (double)pageSize),
            //    PageSize = pageSize,
            //    CurrentCategory = policeno,
            //    CurrentPage = page
            //};
            //return View(model);
        }
        public ActionResult Add()
        {
            var model = new Konut_DigerAddViewModel()
            {
                Konut_Diger = new Konut_Diger(),
                Police = _policeService.GetAll()
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Add(Konut_Diger konutDiger)
        {
            if (ModelState.IsValid)
            {
                _konutDigerService.Add(konutDiger);
                // TempData.Add("message","Poliçe başarıyla eklendi");

            }
            return RedirectToAction("Add");

        }
        public ActionResult Update()
        {
            return View();
        }
    }
}

InsureApp/Views/Konut_Diger/Add.cshtml
@using System.Threading.Tasks
@using InsureApp.Models
@model InsureApp.Models.Konut_DigerAddViewModel

@{
    ViewBag.Title = "Konut Bilgileri Ekleme";
    Layout = "~/Views/_AdminLayout.cshtml";
}

<h2>Konut Bilgileri Ekleme</h2>

<form asp-controller="Konut_Diger" asp-action="Add" method="post">
    
    <div class="form-group">
        <label asp-for="Konut_Diger.Police_no">Poliçe No :</label>
        <select asp-for="Konut_Diger.Police_no" class="form-control h-100"
                asp-items="@(new SelectList(Model.Police,"Police_no","Police_no"))"></select>
        <span asp-validation-for="Konut_Diger.Police_no"></span>
    </div>

    <div class="form-group">
        <label asp-for="Konut_Diger.Adres">Adres :</label>
        <input asp-for="Konut_Diger.Adres" class="form-control" placeholder="Adres" />
        <span asp-validation-for="Konut_Diger.Adres"></span>
    </div>

    <input type="submit" value="EKLE" class="btn btn-xs btn-success" />

</form>

InsureApp/Views/Konut_Diger/Index.cshtml
@using InsureApp.Entities.Concrete
@model InsureApp.Models.Konut_DigerListViewModel

@{
    ViewBag.Title = "Konut İşlemleri";
    Layout = "~/Views/_AdminLayout.cshtml";
}

<h2>Konut Bilgileri Listesi</h2>

<a class="btn btn-xs btn-success" asp-controller="Konut_Diger" asp-action="Add">Konut Bilgileri Ekle</a>
<div>
    <table class="table table-hover table-striped">
        <tr>          
            <td>Poliçe No</td>
            <td>Adres</td>
            <td></td>
            <td></td>
        </tr>
        @foreach (var konutdiger in Model.Konut_Diger) 
        {
        <tr>
            <td>@konutdiger.Police_no</td>
            <td>@konutdiger.Adres</td>

            <td><a class="btn btn-xs btn-info" asp-controller="Admin" asp-action="Update" asp-route-productId="@konutdiger.Konut_id">Update</a></td>
            <td><a class="btn btn-xs btn-danger" asp-controller="Admin" asp-action="Delete" asp-route-productId="@konutdiger.Konut_id">Delete</a></td>
        </tr>
        }
    </table>
</div>

InsureApp/Views/Konut_Diger/Update.cshtml
@using System.Threading.Tasks
@using InsureApp.Models
@model InsureApp.Models.MusteriUpdateViewModel

@{
    ViewBag.Title = "Güncelleme İşlemi";
    Layout = "~/Views/_AdminLayout.cshtml";
}

<h2>Müşteri Güncelle</h2>

<form asp-controller="Admin" asp-action="Update" method="post">
    <div class="form-group">
        <label asp-for="Musteri.Musteri_id"></label>
        <input asp-for="Musteri.Musteri_id" class="form-control" placeholder="Musteri ID" />
        <span asp-validation-for="Musteri.Musteri_id"></span>
    </div>
    <div class="form-group">
        <label asp-for="Musteri.Tc_No"></label>
        <input asp-for="Musteri.Tc_No" class="form-control" placeholder="Tc No:" />
        <span asp-validation-for="Musteri.Tc_No"></span>
    </div>
    <div class="form-group">
        <label asp-for="Musteri.Isim"></label>
        <input asp-for="Musteri.Isim" class="form-control" placeholder="Adı" />
        <span asp-validation-for="Musteri.Isim"></span>
    </div>
    <div class="form-group">
        <label asp-for="Musteri.Soyisim"></label>
        <input asp-for="Musteri.Soyisim" class="form-control" placeholder="Soyadı" />
        <span asp-validation-for="Musteri.Soyisim"></span>
    </div>
    <div class="form-group">
        <label asp-for="Musteri.Tel_no"></label>
        <input asp-for="Musteri.Tel_no" class="form-control" placeholder="Telefon Numarası" />
        <span asp-validation-for="Musteri.Tel_no"></span>
    </div>
    <div class="form-group">
        <label asp-for="Musteri.Adres"></label>
        <input asp-for="Musteri.Adres" class="form-control" placeholder="Adres" />
        <span asp-validation-for="Musteri.Adres"></span>
    </div>
    <div class="form-group">
        <label asp-for="Musteri.Ozel_not"></label>
        <input asp-for="Musteri.Ozel_not" class="form-control" placeholder="Açıklama" />
        <span asp-validation-for="Musteri.Ozel_not"></span>
    </div>

    <input type="hidden" asp-for="Musteri.Musteri_id"/>
    <input type="submit" value="GÜNCELLE" class="btn btn-xs btn-success" />

</form>