InsureApp/Controllers/AdminController.cs
using InsureApp.Business.Abstract;
using InsureApp.Entities.Concrete;
using InsureApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InsureApp.Controllers
{
    public class AdminController:Controller
    {
        private IMusteriService _musteriService;


        public AdminController(IMusteriService musteriService)
        {
            _musteriService = musteriService; 


        }

        public ActionResult Index()
        {
            var musteriListViewModel = new MusteriListViewModel
            {
                Musteri = _musteriService.GetAll()
            };
            return View(musteriListViewModel); 
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(Musteri musteri)
        {
            if (ModelState.IsValid)
            {
                _musteriService.Add(musteri);
                return RedirectToAction("Index");
                //TempData.Add("Mesaj", "Müşteri ekleme işlemi gerçekleşti.");
            }
            return View();
        }


        public ActionResult Update(int musteriId)

        {
            var model = new MusteriUpdateViewModel
            {
                Musteri = _musteriService.GetById(musteriId),
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Update(Musteri musteri)
        {
            if (ModelState.IsValid)
            {
                _musteriService.Update(musteri);
                //TempData.Add("Mesaj", "Müşteri güncelleme işlemi gerçekleşti.");
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int musteriId)
        {
            _musteriService.Delete(musteriId);
            //TempData.Add("Mesaj", "Müşteri silme işlemi gerçekleşti.");
            return RedirectToAction("Index");
        }
    }
}

InsureApp/Controllers/CariController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using InsureApp.Business.Abstract;
using InsureApp.Entities.Concrete;
using InsureApp.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using SelectPdf;


namespace InsureApp.Controllers

{ 
    public class CariController : Controller
    {
        private IOdemelerService _odemelerService;
        private IMusteriService _musteriservice;
        private IPoliceService _policeService;
        private readonly IHostingEnvironment _hostingEnvironment;

        public CariController(IOdemelerService odemelerService,
                                  IPoliceService policeService,
                                  IMusteriService musteriService,
                                  IHostingEnvironment hostingEnvironment)
        {
            _odemelerService = odemelerService;
            _policeService = policeService;
            _musteriservice = musteriService;
            _hostingEnvironment = hostingEnvironment;
        }

        public ActionResult ExportToPDF(int musteri = 0)
        {
            /* URL den PDF URETME olayı burada
            // instantiate a html to pdf converter object
            HtmlToPdf converter = new HtmlToPdf();

            // create a new pdf document converting an url
            PdfDocument doc = converter.ConvertUrl("http://localhost:49737/Cari/Index");

            // save pdf document
            byte[] pdf = doc.Save();

            // close pdf document
            doc.Close();

            // return resulted pdf document
            FileResult fileResult = new FileContentResult(pdf, "application/pdf");
            fileResult.FileDownloadName = "Document.pdf";
            return fileResult;

            */


            
            // burada sayfa boyutu veriyorsun aynen printerdaki gibi
            PdfPageSize pageSize = (PdfPageSize)Enum.Parse(typeof(PdfPageSize),
                "A4", true);

            //burada da yatay dikey secenegi aynen printerdaki gibi
            PdfPageOrientation pdfOrientation =
                (PdfPageOrientation)Enum.Parse(typeof(PdfPageOrientation),
                    "Portrait", true);

            int webPageWidth = 1024;


            int webPageHeight = 0;

            // instantiate a html to pdf converter object
            HtmlToPdf converter = new HtmlToPdf();

            // set converter options
            converter.Options.PdfPageSize = pageSize;
            converter.Options.PdfPageOrientation = pdfOrientation;
            converter.Options.WebPageWidth = webPageWidth;
            converter.Options.WebPageHeight = webPageHeight;

            // create a new pdf document converting an url
            var odeme = _odemelerService.GetAll();
            StringBuilder sb = new StringBuilder();
            sb.Append("<html><body><table border='1' width='100%'><tr style='color:red'><td style='color:blue'>Poliçe No</td> <td> Musteri Adı </td> <td> Ödeme Tarihi </td><td> Ödenen Tutar </td><td> Borç </td> <td> Alacak </td></tr>");

            foreach (Odemeler item in odeme)
            {
                sb.Append("<tr>");
                var alacak = 0;
                var borc = 0 - item.Odenen_tutar; 
                if (item.Odenen_tutar > 0)
                {
                    borc = 0;
                    alacak = item.Odenen_tutar - 0;
                }
                else
                { 
                    borc = 0 - item.Odenen_tutar;
                }


                sb.Append("<td> " + item.Police_no + "</td>");
                sb.Append("<td> " + "Hakan Mehmet" + "</td>"); 
                sb.Append("<td> " + item.Odeme_tarihi +"</td>");
                sb.Append("<td> " + item.Odenen_tutar + "</td>");
                sb.Append("<td> " + borc + " </td>");
                sb.Append("<td> "+"0" +"</td>");
                sb.Append("</tr>");
            }
            sb.Append("</table></body></html>");
            PdfDocument doc = converter.ConvertHtmlString(sb.ToString(), "");

            // save pdf document
            byte[] pdf = doc.Save();

            // close pdf document
            doc.Close();

            // return resulted pdf document
            FileResult fileResult = new FileContentResult(pdf, "application/pdf");
            fileResult.FileDownloadName = "Document.pdf";
            return fileResult;

           





            /*
            //Initialize HTML to PDF converter 
            HtmlToPdfConverter htmlConverter = new HtmlToPdfConverter();
            WebKitConverterSettings settings = new WebKitConverterSettings();
            //Set WebKit path
            settings.WebKitPath = Path.Combine(_hostingEnvironment.ContentRootPath, "QtBinariesWindows");
            //Assign WebKit settings to HTML converter
            htmlConverter.ConverterSettings = settings;
            //Convert URL to PDF
            PdfDocument document = htmlConverter.Convert("~/Views/Cari/Index.cshtml");
            MemoryStream stream = new MemoryStream();
            document.Save(stream);
            return File(stream.ToArray(), System.Net.Mime.MediaTypeNames.Application.Pdf, "Sample.pdf");
            */
        }

        public ActionResult Index(int page = 1, int musteri = 0)
        {
            int pageSize = 10;
            var odeme = _odemelerService.GetByMusteriId(musteri);
            CariListViewModel model = new CariListViewModel()
            {
                Odemeler = FixModel(odeme.Skip((page - 1) * pageSize).Take(pageSize).ToList()),
                PageCount = (int)Math.Ceiling(odeme.Count / (double)pageSize),
                PageSize = pageSize,
                CurrentCategory = musteri,
                CurrentPage = page
            };
            return View(model);
        }

        private List<OdemelerModel> FixModel(List<Odemeler> toList)
        {
            var result = new List<OdemelerModel>();
            foreach (var item in toList)
            {
                var row = new OdemelerModel();
                var musteri = _musteriservice.GetById(item.Musteri_id);
                var police = _policeService.GetById(item.Police_no);

                row.SigortaBedeli = police.Sigorta_bedeli;
                row.Ad = musteri.Isim;
                row.Soyad = musteri.Soyisim;
                row.FullName = string.Format("{0} {1}", row.Ad, row.Soyad);
                //row.Musteri_id = item.Musteri_id;
                row.Odeme_id = item.Odeme_id;
                row.Odeme_tarihi = item.Odeme_tarihi;
                row.Odenen_tutar = item.Odenen_tutar;
                row.Police_no = police.Police_no;

                result.Add(row);
            }

            return result;
        }


        private List<MusteriModel> FixMusterModel(List<Musteri> list)
        {
            var result = new List<MusteriModel>();
            foreach (var item in list)
            {
                var row = new MusteriModel();
                //row.FullName = item.Isim + item.Soyisim;
                row.FullName = string.Format("{0}  {1}", item.Isim, item.Soyisim);
                row.Musteri_id = item.Musteri_id;

                result.Add(row);
            }

            return result;
        }

        [HttpPost]
        public ActionResult Add(Odemeler odemeler)
        {
            if (ModelState.IsValid)
            {
                _odemelerService.Add(odemeler);

                // TempData.Add("message","Poliçe başarıyla eklendi");

            }

            return RedirectToAction("Add");

        }
        public ActionResult Update(Odemeler odemeler)
        {
            //if (ModelState.IsValid)
            //{
            //    _odemelerService.Update(odemeler);
            //    //TempData.Add("Mesaj", "Müşteri güncelleme işlemi gerçekleşti.");
            //}
            //return RedirectToAction("Index");
            return View();
        }
        //public ActionResult Delete(int odemeID)
        //{
        //    _odemelerService.Delete(odemeID);
        //    //TempData.Add("Mesaj", "Müşteri silme işlemi gerçekleşti.");
        //    return RedirectToAction("Index");
        //}
    }
}

InsureApp/Controllers/PoliceController.cs
using InsureApp.Business.Abstract;
using InsureApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InsureApp.Entities.Concrete;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace InsureApp.Controllers
{
    public class PoliceController:Controller
    {
        private IPoliceService _policeService;
        private IPoliceTuruService _policeturuservice;
        private IMusteriService _musteriservice;
        private IAracService _aracService;
        private IKonut_DigerService _konutDigerService;
        private IOdemelerService _odemelerService;

        public PoliceController(IPoliceService policeService, 
                                IPoliceTuruService policeturuService, 
                                IMusteriService musteriService,
                                IAracService aracService,
                                IKonut_DigerService konutDigerService,
                                IOdemelerService odemelerService)
        {
            _policeService = policeService;
            _policeturuservice = policeturuService;
            _musteriservice = musteriService;
            _aracService = aracService;
            _konutDigerService = konutDigerService;
            _odemelerService = odemelerService;
        }

        public ActionResult Index(int page = 1, int policeturu = 0)
        {
            int pageSize = 10;
            var police = _policeService.GetByPolice_Turu(policeturu);
            var policTuru = _policeturuservice.GetByPolice_Turu(policeturu).FirstOrDefault();
            PoliceListViewModel model = new PoliceListViewModel
            {
                Police = FixModel(police.Skip((page -1) * pageSize).Take(pageSize).ToList()),
                PageCount = (int)Math.Ceiling(police.Count / (double)pageSize),
                PageSize = pageSize,
                CurrentCategory = policTuru != null ? policTuru.Policetur_id : 0,
                CurrentCategoryText = policTuru != null ? policTuru.Police_turu : string.Empty,
                CurrentPage = page
            };
            return View(model);
        }

        private List<PoliceModel> FixModel(List<Police> toList)
        {
            var result = new List<PoliceModel>();
            foreach (var item in toList)
            {
                var row = new PoliceModel();
                var musteri = _musteriservice.GetById(item.Musteri_id);
                var policeturu = _policeturuservice.GetById(item.Policetur_id);

                row.PoliceTuru = policeturu.Police_turu;
                row.Ad = musteri.Isim;
                row.Soyad = musteri.Soyisim;
                row.Policetur_id = policeturu.Policetur_id;
                row.Baslangic_tarihi = item.Baslangic_tarihi;
                row.Bitis_tarihi = item.Bitis_tarihi;
                row.Vize_tarihi = item.Vize_tarihi;
                row.Sigorta_bedeli = item.Sigorta_bedeli;
                row.Police_no = item.Police_no;
                row.FullName = string.Format("{0} {1}",row.Ad,row.Soyad);
                result.Add(row);
            }

            return result;
        }


        public ActionResult Add()
        {
            var model = new PoliceAddViewListModel
            {
                Police = new Police(),
                PoliceTuru = _policeturuservice.GetAll(),
                MusterilerList = FixMusterModel( _musteriservice.GetAll())
            };
            return View(model);
        }

        private List<MusteriModel> FixMusterModel(List<Musteri> list)
        {
            var result = new List<MusteriModel>();
            foreach (var item in list)
            {
               var row = new MusteriModel();
               //row.FullName = item.Isim + item.Soyisim;
               row.FullName = string.Format("{0}  {1}", item.Isim, item.Soyisim);
               row.Musteri_id = item.Musteri_id;
               result.Add(row);
            }

            return result;
        }

        [HttpPost]
        public ActionResult Add(Police police)
        {
            if (ModelState.IsValid)
            {

                
                _policeService.Add(police);
                // TempData.Add("message","Poliçe başarıyla eklendi");
                
            }
            return RedirectToAction("Add");

        }

        public ActionResult Update(int police_No)
             
        {
            var model = new PoliceUpdateViewModel()
            {
                Police = _policeService.GetById(police_No),
                Musteri = _musteriservice.GetAll(),
                PoliceTuru = _policeturuservice.GetAll()
               
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Update(Police police)
        {
            if (ModelState.IsValid)
            {
                _policeService.Update(police);
                //TempData.Add("Mesaj", "Müşteri güncelleme işlemi gerçekleşti.");
            }
            return RedirectToAction("Update");
        }

        public ActionResult Delete(int Police_no)
        {
            _aracService.DeleteByPoliceId(Police_no);
            _konutDigerService.DeleteByPoliceId(Police_no);
            _odemelerService.DeleteByPoliceId(Police_no);
            _policeService.Delete(Police_no);
            //TempData.Add("Mesaj", "Müşteri silme işlemi gerçekleşti.");
            return RedirectToAction("Index");
        }
    }
}

InsureApp/Views/_AccountLayout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewBag.Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <link rel="apple-touch-icon" sizes="76x76" href="/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="/assets/img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Light Bootstrap Dashboard - Free Bootstrap 4 Admin Dashboard by Creative Tim</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <!-- CSS Files -->
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/assets/css/light-bootstrap-dashboard.css?v=2.0.1" rel="stylesheet" />
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href="/assets/css/demo.css" rel="stylesheet" /> 
    
</head>
<body>
<div class="col-md-12">
    
    @RenderBody()
</div>


        
            <footer class="footer">
            <div class="container">
                <nav>
                    <ul class="footer-menu">
                        <li>
                            <a class="nav-link" asp-controller="Admin" asp-action="Index">
                                MÜŞTERİ İŞLEMLERİ
                            </a>
                        </li>
                        <li>
                            <a class="nav-link" asp-controller="Police" asp-action="Index">
                                SİGORTA İŞLEMLERİ
                            </a>
                        </li>
                        <li>
                            <a class="nav-link" asp-controller="Cari" asp-action="Index">
                                CARİ İŞLEMLER
                            </a>
                        </li>
                        <li>
                            <a class="nav-link active" href="mailto:m_ozer_02@hotmail.com">
                                YARDIM
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-center">
                        ©
                        <script>
                            document.write(new Date().getFullYear())
                        </script>
                        <a href="#">M&F YAZILIM</a>, Version 1.0
                    </p>
                </nav>
            </div>
        </footer>
    
    <!--   -->
    <!-- <div class="fixed-plugin">
        <div class="dropdown show-dropdown">
            <a href="#" data-toggle="dropdown">
                <i class="fa fa-cog fa-2x"> </i>
            </a>

            <ul class="dropdown-menu">
                <li class="header-title"> Sidebar Style</li>
                <li class="adjustments-line">
                    <a href="javascript:void(0)" class="switch-trigger">
                        <p>Background Image</p>
                        <label class="switch">
                            <input type="checkbox" data-toggle="switch" checked="" data-on-color="primary" data-off-color="primary"><span class="toggle"></span>
                        </label>
                        <div class="clearfix"></div>
                    </a>
                </li>
                <li class="adjustments-line">
                    <a href="javascript:void(0)" class="switch-trigger background-color">
                        <p>Filters</p>
                        <div class="pull-right">
                            <span class="badge filter badge-black" data-color="black"></span>
                            <span class="badge filter badge-azure" data-color="azure"></span>
                            <span class="badge filter badge-green" data-color="green"></span>
                            <span class="badge filter badge-orange" data-color="orange"></span>
                            <span class="badge filter badge-red" data-color="red"></span>
                            <span class="badge filter badge-purple active" data-color="purple"></span>
                        </div>
                        <div class="clearfix"></div>
                    </a>
                </li>
                <li class="header-title">Sidebar Images</li>

                <li class="active">
                    <a class="img-holder switch-trigger" href="javascript:void(0)">
                        <img src="../assets/img/sidebar-1.jpg" alt="" />
                    </a>
                </li>
                <li>
                    <a class="img-holder switch-trigger" href="javascript:void(0)">
                        <img src="../assets/img/sidebar-3.jpg" alt="" />
                    </a>
                </li>
                <li>
                    <a class="img-holder switch-trigger" href="javascript:void(0)">
                        <img src="..//assets/img/sidebar-4.jpg" alt="" />
                    </a>
                </li>
                <li>
                    <a class="img-holder switch-trigger" href="javascript:void(0)">
                        <img src="../assets/img/sidebar-5.jpg" alt="" />
                    </a>
                </li>

                <li class="button-container">
                    <div class="">
                        <a href="http://www.creative-tim.com/product/light-bootstrap-dashboard" target="_blank" class="btn btn-info btn-block btn-fill">Download, it's free!</a>
                    </div>
                </li>

                <li class="header-title pro-title text-center">Want more components?</li>

                <li class="button-container">
                    <div class="">
                        <a href="http://www.creative-tim.com/product/light-bootstrap-dashboard-pro" target="_blank" class="btn btn-warning btn-block btn-fill">Get The PRO Version!</a>
                    </div>
                </li>

                <li class="header-title" id="sharrreTitle">Thank you for sharing!</li>

                <li class="button-container">
                    <button id="twitter" class="btn btn-social btn-outline btn-twitter btn-round sharrre"><i class="fa fa-twitter"></i> · 256</button>
                    <button id="facebook" class="btn btn-social btn-outline btn-facebook btn-round sharrre"><i class="fa fa-facebook-square"></i> · 426</button>
                </li>
            </ul>
        </div>
    </div>
    -->

</body>
<!--   Core JS Files   -->
<script src="../assets/js/core/jquery.3.2.1.min.js" type="text/javascript"></script>
<script src="../assets/js/core/popper.min.js" type="text/javascript"></script>
<script src="../assets/js/core/bootstrap.min.js" type="text/javascript"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="../assets/js/plugins/bootstrap-switch.js"></script>
<!--  Google Maps Plugin    -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<!--  Chartist Plugin  -->
<script src="../assets/js/plugins/chartist.min.js"></script>
<!--  Notifications Plugin    -->
<script src="../assets/js/plugins/bootstrap-notify.js"></script>
<!-- Control Center for Light Bootstrap Dashboard: scripts for the example pages etc -->
<script src="../assets/js/light-bootstrap-dashboard.js?v=2.0.1" type="text/javascript"></script>
<!-- Light Bootstrap Dashboard DEMO methods, don't include it in your project! -->
<script src="../assets/js/demo.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        // Javascript method's body can be found in assets/js/demos.js
        demo.initDashboardPageCharts();

        demo.showNotification();

    });
</script>
</html>